/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.chagnon.aoc2023.days;

import java.util.List;
import dev.chagnon.aoc2023.DayRunner;
import lombok.ToString;

public class Day03 implements DayRunner {

    @Override
    public String part1(String input) {
        return "TODO";
    }

    @Override
    public String part2(String input) {
        return "TODO";
    }

}
