/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.chagnon.aoc2023;

public interface DayRunner {

    String part1(String input);

    String part2(String input);

}
