/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.chagnon.aoc2023;

import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.concurrent.Callable;
import com.google.common.io.Resources;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(name = "run", mixinStandardHelpOptions = true,
        description = "Prints the checksum (SHA-256 by default) of a file to STDOUT.")
public class Main implements Callable<Integer> {

    @Option(names = {"-d", "--day"}, description = "The day to run")
    private Day dayInput;

    @Override
    public Integer call() throws Exception {
        List<Day> toRun = dayInput != null ? List.of(dayInput) : List.of(Day.values());

        for (Day day : toRun) {
            System.out.println(String.format("== Day %02d ==", day.getN()));

            URL inputPath = Resources.getResource(String.format("input%02d", day.getN()));
            String input = Resources.toString(inputPath, StandardCharsets.UTF_8);

            String result1 = day.getRunner().part1(input);
            System.out.println(String.format("Part 1: \u001B[32m%s\u001B[0m", result1));

            String result2 = day.getRunner().part2(input);
            System.out.println(String.format("Part 2: \u001B[32m%s\u001B[0m", result2));

            System.out.println();
        }

        return 0;

    }

    public static void main(String[] args) {
        System.out.println("""

                ***************************
                *   ADVENT OF CODE 2023   *
                ***************************
                """);

        var commandLine = new CommandLine(new Main());
        commandLine.registerConverter(Day.class, s -> Day.fromString(s));
        int exitCode = commandLine.execute(args);
        System.exit(exitCode);
    }
}
